import type { Collection } from "./types";
import { products } from "./products";

function productIdsForCollection(id: string) {
  return products.filter((product) => product.collections.includes(id)).map((product) => product.id);
}

// Collections express a customer intent, independently from product categories.
export const collections: Collection[] = [
  { id: "minimal", slug: "minimal", kind: "style", name: { en: "Minimal", zh: "极简" }, shortDescription: { en: "Quiet color, considered detail.", zh: "克制的色彩与用心的细节。" }, productIds: productIdsForCollection("minimal"), visual: "press-on", featured: true, seo: { title: { en: "Minimal Nail Collection", zh: "极简美甲系列" }, description: { en: "Explore a minimal nail collection concept.", zh: "探索极简美甲系列概念。" }, indexable: false }, isMock: true },
  { id: "french", slug: "french", kind: "style", name: { en: "French", zh: "法式" }, shortDescription: { en: "A classic direction, open to reinvention.", zh: "经典风格的当代表达。" }, productIds: productIdsForCollection("french"), visual: "gel", featured: true, seo: { title: { en: "French Nail Collection", zh: "法式美甲系列" }, description: { en: "Explore a French nail collection concept.", zh: "探索法式美甲系列概念。" }, indexable: false }, isMock: true },
  { id: "chrome", slug: "chrome", kind: "style", name: { en: "Chrome", zh: "镜面" }, shortDescription: { en: "Light-catching finishes for a modern edit.", zh: "适合现代系列的光感效果。" }, productIds: productIdsForCollection("chrome"), visual: "accessories", featured: true, seo: { title: { en: "Chrome Nail Collection", zh: "镜面美甲系列" }, description: { en: "Explore a chrome nail collection concept.", zh: "探索镜面美甲系列概念。" }, indexable: false }, isMock: true },
  { id: "cat-eye", slug: "cat-eye", kind: "style", name: { en: "Cat Eye", zh: "猫眼" }, shortDescription: { en: "Dimensional color with a distinct point of view.", zh: "具有层次感的色彩表达。" }, productIds: productIdsForCollection("cat-eye"), visual: "gel", featured: true, seo: { title: { en: "Cat Eye Nail Collection", zh: "猫眼美甲系列" }, description: { en: "Explore a cat eye nail collection concept.", zh: "探索猫眼美甲系列概念。" }, indexable: false }, isMock: true },
  { id: "wedding", slug: "wedding", kind: "occasion", name: { en: "Wedding", zh: "婚礼" }, shortDescription: { en: "A refined edit for meaningful occasions.", zh: "为重要场合准备的精致系列。" }, productIds: productIdsForCollection("wedding"), visual: "press-on", featured: true, seo: { title: { en: "Wedding Nail Collection", zh: "婚礼美甲系列" }, description: { en: "Explore a wedding nail collection concept.", zh: "探索婚礼美甲系列概念。" }, indexable: false }, isMock: true },
  { id: "inclusive-color-stories", slug: "inclusive-color-stories", kind: "audience", name: { en: "Inclusive Color Stories", zh: "多元肤色灵感" }, shortDescription: { en: "Color directions considered across diverse skin tones.", zh: "考虑多元肤色表达的色彩方向。" }, productIds: productIdsForCollection("inclusive-color-stories"), visual: "gel", featured: true, seo: { title: { en: "Inclusive Nail Color Stories", zh: "多元肤色美甲色彩系列" }, description: { en: "Explore inclusive nail color concepts.", zh: "探索包容多元肤色的美甲色彩概念。" }, indexable: false }, isMock: true },
  { id: "us-market-edit", slug: "us-market-edit", kind: "market", name: { en: "US Market Edit", zh: "美国市场精选方向" }, shortDescription: { en: "A planning space for future US assortments.", zh: "用于未来美国市场产品组合规划的主题。" }, productIds: productIdsForCollection("us-market-edit"), visual: "press-on", featured: false, seo: { title: { en: "US Market Nail Edit", zh: "美国市场美甲系列方向" }, description: { en: "An upcoming US market collection concept.", zh: "即将完善的美国市场美甲系列概念。" }, indexable: false }, isMock: true },
  { id: "europe-market-edit", slug: "europe-market-edit", kind: "market", name: { en: "European Market Edit", zh: "欧洲市场精选方向" }, shortDescription: { en: "A planning space for future European assortments.", zh: "用于未来欧洲市场产品组合规划的主题。" }, productIds: productIdsForCollection("europe-market-edit"), visual: "gel", featured: false, seo: { title: { en: "European Market Nail Edit", zh: "欧洲市场美甲系列方向" }, description: { en: "An upcoming European market collection concept.", zh: "即将完善的欧洲市场美甲系列概念。" }, indexable: false }, isMock: true },
];

export function getFeaturedCollections() { return collections.filter((collection) => collection.featured); }
export function getCollectionBySlug(slug: string) { return collections.find((collection) => collection.slug === slug); }
